### ISSUE TITLE
Can't run either sclang or scsynth on windows 10.

### ISSUE THREAD

**Issue by Normalised** [crucialfelix/supercolliderjs#20]
From either the npm install and a clone of this repo I can't get anything to run.

The install / build runs fine.

* running : node bin/sclang.js

```
{ stdout: 'compiling class library...\r\n\n...\r\n\n\tNumPrimitives = 644\r\n\tcompiling dir: \'C:\\audio\\apps\\SuperCollider-3.6.6\\SCClassLibrary\'\r\n\tcompiling dir: \'C:\\Users\\martin\\AppData\\Local\\SuperCollider\\Extensions\'\r\n\tcompiling dir: \'C:\\dev\\workspaces\\github\\supercolliderjs\\lib\\sc-classes\'\r\n\tpass 1 done\r\n\nERROR: Variable \'cache\' not defined.\r\n  in file \'C:\\dev\\workspaces\\github\\supercolliderjs\\lib\\sc-classes\\SystemOverwrites\\plusQuarks.sc\'\r\n  line 15 char 25:\r\n\r\n  \t\tcache = Dictionary.new;\r\n                           \r\n  \t}\r\n-----------------------------------\r\n',
  errors: [],
  extensionErrors: [],
  duplicateClasses: [],
  dirs:
   [ 'C:\\audio\\apps\\SuperCollider-3.6.6\\SCClassLibrary',
     'C:\\Users\\martin\\AppData\\Local\\SuperCollider\\Extensions',
     'C:\\dev\\workspaces\\github\\supercolliderjs\\lib\\sc-classes' ] }
Trace
    at C:\dev\workspaces\github\supercolliderjs\bin\sclang.js:71:11
    at tryCatcher (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\promise.js:488:31)
    at Promise._settlePromise (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\promise.js:545:18)
    at Promise._settlePromise0 (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\promise.js:590:10)
    at Promise._settlePromises (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\promise.js:669:18)
    at Async._drainQueue (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

* running : node bin/scsynth.js

SuperCollider starts up but then an error occurs :

```
stdout :
           Device options:
             - MME : Microsoft Sound Mapper - Inp
stdout : ut   (device #0 with 2 ins 0 outs)
             - MME : Analog (1+2) (RME HDSP 9632)   (device #1 with 2 ins 0 outs)
             - MME : Microphone (3- Logitech USB Hea   (device #2 with 2 ins 0 outs)
             - MME : Microsoft Sound Mapper - Output   (device #3 with 0 ins 2 outs)
             - MME : Analog (1+2) (RME HDSP 9632)   (device #4 with 0 ins 2 outs)
             - MME : Speakers (3- Logitech USB Heads   (device #5 with 0 ins 2 outs)
             - MME : DELL U2414H-C (NVIDIA High Defi   (device #6 with 0 ins 2 outs)
             - MME : Realtek Digital Output (Realtek   (device #7 with 0 ins 2 outs)
             - ASIO : ASIO Hammerfall DSP   (device #8 with 12 ins 12 outs)

           Booting with:
             In: MME : Analog (1+2) (RME HDSP 9632)
             Out: MME : Analog (1+2) (RME HDSP 9632)
stdout :   Sample rate:
stdout : 44100.000
             Latency (in/out): 0.013 / 0.091 sec
           SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
stdout : SuperCollider 3 se
stdout : rver ready.
undefined
C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:45
        fn = function () { throw arg; };
                           ^

Error
    at Error (native)
    at C:\dev\workspaces\github\supercolliderjs\lib\dryadic\helpers.js:29:9
    at fireRejectionEvent (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\debuggability.js:409:17)
    at Promise._notifyUnhandledRejection (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\debuggability.js:46:9)
    at Async._drainQueue (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:130:12)
    at Async._drainQueues (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:138:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\dev\workspaces\github\supercolliderjs\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 %
 ```

Im more than happy to try and track down how and why the scsynth error is occurring if you can give me a rough guide to the execution order of the code and how its structured.

thanks.

**Comment by Normalised** [comment]
Ok, looks like the initial problem is the stdout observer is trying to match on the complete string 'SuperCollider 3 server ready' but the actual stdout text is split into chunks.
How its split is also not consistent, I get different results each time I run it.

So I guess the output will need to be buffered so the text.match(/SuperCollider 3 server ready/) code works.

**Comment by Normalised** [comment]
https://github.com/crucialfelix/supercolliderjs/pull/21

**Comment by crucialfelix** [comment]
sclang: the problem is that you are using 3.6  and supercollider-js only officially supports 3.7 now. 

I realize we don't have a formal 3.7 released yet and no windows build for download.

But this is the only spot I can notice that would stop it from being used with 3.6.6 so I can do a workaround in that method. Quarks wouldn't work (the new version is much better in 3.7) but the rest should work.

Your Quarks class doesn't have a 'cache' variable.

    ERROR: Variable \'cache\' not defined

**Comment by Normalised** [comment]
Ok thanks.

**Comment by crucialfelix** [comment]
Done and released. 

Let me know any other windows issues or general feedback. Thanks !
