### ISSUE TITLE
Getting Started 

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/supercolliderjs#23]
Hello, 

I'm just getting into supercollider js. I installed the packages fine and got to the point where you say "In your code require the package:" and then some code. Where does that code go and how exactly do you run it? I'm assuming it doesn't have to be in the same folder as the modules since they were installed locally. I'm pretty new to node, a small bit of guidance would be helpful. 

...edit: figured the above bit out pretty quickly but i'm still curious about the other question. 

I'm eventually interested in possibly trying to use this with electron to make a standalone. Would this be possible?

thanks!

**Comment by tatecarson** [comment]
Also trying to run the api example and getting this error: `tate-2:examples tatecarson$ node call-api-from-node.js
Unhandled Rejection: [TypeError: SCAPI is not a function] TypeError: SCAPI is not a function
    at /Users/tatecarson/node_modules/supercolliderjs/examples/call-api-from-node.js:27:15
    at tryCatcher (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/tatecarson/node_modules/supercolliderjs/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

this is after running API.mountDuplexOSC in supercollider

**Comment by crucialfelix** [comment]
See https://github.com/experimentalDataAesthetics/play-splom for a working electron example app

**Comment by crucialfelix** [comment]
I am going to rework all the examples and greatly expand them, move them into a separate repo.

So you understood that you write a `my-thing.js` and run it with `node my-thing.js`

**Comment by crucialfelix** [comment]
Closing this now that I have some documentation and guides up. 

They aren't finished or perfect though. I'm trying to find the time for another big writing session.

https://crucialfelix.github.io/supercolliderjs/
https://crucialfelix.gitbooks.io/supercollider-js-guide/content/
https://crucialfelix.github.io/supercolliderjs/api/
