### ISSUE TITLE
scsynth not found on Linux

### ISSUE THREAD

**Issue by snappizz** [crucialfelix/supercolliderjs#25]
I'm on Ubuntu 16.04. supercolliderjs doesn't seem to find scsynth even if it's in my PATH:

```
$ which scsynth
/home/nathan/usr/local/bin/scsynth
```

```
var sc = require("supercolliderjs");
sc.server.boot();

Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> error  : Failed to boot /usr/local/bin/scsynth
Unhandled rejection Error: Failed to boot /usr/local/bin/scsynth
    at ServerPlus._spawnProcess (/home/nathan/bla/node_modules/supercolliderjs/lib/server/server.js:362:15)
    at /home/nathan/bla/node_modules/supercolliderjs/lib/server/server.js:307:18
    at Promise._execute (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:77:14)
    at ServerPlus.boot (/home/nathan/bla/node_modules/supercolliderjs/lib/server/server.js:303:14)
    at /home/nathan/bla/node_modules/supercolliderjs/lib/server/ServerPlus.js:529:14
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/nathan/bla/node_modules/supercolliderjs/node_modules/bluebird/js/release/async.js:17:14)

Error: spawn /usr/local/bin/scsynth ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

Of course, I can fix this by manually setting the correct path in the options with `sc.server.boot({ scsynth: ... })`, so it's not a huge issue.

**Comment by crucialfelix** [comment]
It needs an explicit path. Only linux has scsynth installed on your PATH. OS X and windows do not do this.

supercollider.js is also intended to be used with an included portable version of scsynth.

You can use a config file ~/.supercollider.yaml so you don't have to set it in your code.
See https://crucialfelix.gitbooks.io/supercollider-js-guide/content/lang/install-and-configuration.html
