### ISSUE TITLE
Reimplement or replace osc-min

### ISSUE THREAD

**Issue by crucialfelix** [crucialfelix/supercolliderjs#59]
- [ ] Search for a replacement
- [ ] Port to typescript as osc-messages or?

Immediate blocker:

Error building time tags:

Unhandled rejection RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received 3780374514
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:623:3)
    at Buffer.writeInt32BE (internal/buffer.js:711:10)
    at Object.module.exports.(anonymous function) [as packInt32] (/Users/crucialfelix/code/supercolliderjs/node_modules/binpack/index.js:35:72)
    at Object.exports.toTimetagBuffer (/Users/crucialfelix/code/supercolliderjs/node_modules/osc-min/lib/osc-utilities.js:191:34)
    at Object.exports.toOscBundle (/Users/crucialfelix/code/supercolliderjs/node_modules/osc-min/lib/osc-utilities.js:600:26)
    at Object.exports.toOscPacket (/Users/crucialfelix/code/supercolliderjs/node_modules/osc-min/lib/osc-utilities.js:620:24)
    at Object.exports.toBuffer (/Users/crucialfelix/code/supercolliderjs/node_modules/osc-min/lib/index.js:143:18)
    at SendOSC.send.on.bundle (/Users/crucialfelix/code/supercolliderjs/packages/server/lib/server.js:125:33)
    at SendOSC.emit (events.js:194:15)
    at SendOSC.bundle (/Users/crucialfelix/code/supercolliderjs/packages/server/lib/internals/SendOSC.js:38:14)
    at scserver (/Users/crucialfelix/code/supercolliderjs/packages/dryadic-supercollider/lib/middleware/scserver.js:84:35)
    at /Users/crucialfelix/code/supercolliderjs/node_modules/dryadic/lib/CommandNode.js:137:16
    at Array.map (<anonymous>)
    at CommandNode.execute (/Users/crucialfelix/code/supercolliderjs/node_modules/dryadic/lib/CommandNode.js:136:31)
    at CommandNode.call (/Users/crucialfelix/code/supercolliderjs/node_modules/dryadic/lib/CommandNode.js:99:27)

**Comment by crucialfelix** [comment]
Fixed in 715cfcc1176578caa02633cd43afeaf98fa64a72
